# Taps
tap "caskroom/cask"
tap "homebrew/bundle"
tap "cask-fonts"

# Developer Tools
brew "git"
brew "clojure/tools/clojure"
brew "tree"
brew "zsh"
brew "mas"
brew "zsh-completions"
brew "coreutils"
brew "findutils"
brew "bash"
brew "wget"
brew "diff-so-fancy"
brew "python3"
brew "duti"
brew "yarn"
brew "tmux"
brew "gh"
brew "jenv"
brew "neovim"

# Install casks items (apps, fonts etc)
cask "google-chrome"
cask "firefox"
cask "iterm2"
cask "slack"
cask "dropbox"
cask "vagrant"
cask "virtualbox"
cask "virtualbox-extension-pack"
cask "vlc"
cask "atom"
cask "vagrant-manager"
cask "font-meslo-lg-nerd-font"
