# Taps
tap "homebrew/cask"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "clojure/tools"

# Developer Tools
brew "git"
brew "zsh-syntax-highlighting"
brew "ccls"
brew "clojure/tools/clojure"
brew "borkdude/brew/babashka"
brew "borkdude/brew/clj-kondo"
brew "clojure-lsp/brew/clojure-lsp-native"
brew "tree"
brew "zsh"
brew "mas"
brew "zsh-completions"
brew "coreutils"
brew "findutils"
brew "bash"
brew "wget"
brew "diff-so-fancy"
brew "python3"
brew "duti"
brew "yarn"
brew "tmux"
brew "gh"
brew "jenv"

# nvim
brew "neovim"
brew "fd"
brew "ripgrep"
cask "font-meslo-lg-nerd-font"

# Install casks items (apps, fonts etc)
cask "google-chrome"
cask "firefox"
cask "slack"
cask "dropbox"
cask "vlc"
