;; -*- mode: emacs-lisp; -*-

;; emacs package repositories
(source melpa)
(source marmalade)
(source org)
(source gnu)

;; Core --- core/core.el - requirements
(depends-on "color-theme")          ; not currently used
(depends-on "exec-path-from-shell") ; core-os-osx.el
(depends-on "helm")                 ; core-helm.el
(depends-on "try")                  ; not currently used
(depends-on "use-package")          ; everywhere
(depends-on "which-key")            ; core-which-key.el
(depends-on "cl-lib")               ; core-helm.el
(depends-on "buffer-move")          ; core-buffer-move.el
